services:
  - type: web
    name: truemarket
    runtime: image
    repo: https://github.com/Mdav10/TrueMarket
    plan: free
    branch: main
    dockerCommand: gunicorn app:app --bind 0.0.0.0:10000
    envVars:
      - key: DATABASE_URL
        value: postgresql://mymarket_8q19_user:Hs2KnIFTlDPiz1vWfrPnLQ2dZUwhfN7B@dpg-d8i4gfmq1p3s73ebd8a0-a/mymarket_8q19
